spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: qlqjs123
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show_sql: true

jwt:
  secretKey: Y2hhdHNlcnZlcnNjcmV0YWNjZXNzdG9rZW5jaGF0c2VydmVyc2NyZXRhY2Nlc3N0b2tlbmNoYXRzZXJ2ZXJzY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # 3000 min